services:
  - type: web
    name: media-archive-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://username:password@cluster.mongodb.net/database
      - key: PORT
        value: 10000